@echo off
rem ===================================================================
rem  defaults for every other .bat in this folder, which all call this
rem  one first. do not edit this file on the test machine: put the local
rem  values in _local.bat instead, it is ignored by git.
rem ===================================================================

rem git bash / msys ships its own find, sort and friends, and puts them ahead of the windows
rem ones on PATH. the msys find does not understand /i, so `tasklist | find /i` fails there.
rem every script in this folder runs inside setlocal, so this stays in the script
set "PATH=%SystemRoot%\System32;%SystemRoot%;%SystemRoot%\System32\Wbem;%PATH%"

rem full path to the gguf
set "MODEL=C:\models\qwen3-next.gguf"

rem plain text file for the quality runs (get-wikitext.bat downloads one)
set "PPLFILE=%~dp0wikitext-2-raw\wiki.test.raw"

rem build directory, created by 00-build.bat
set "BUILD=%~dp0..\..\build-win"

rem backend for cmake. auto picks from what the machine has: nvcc or CUDA_PATH -> cuda,
rem else VULKAN_SDK or glslc -> vulkan, else a cpu only build. cuda wins when both are
rem installed. pin it instead of auto to decide here:
rem   strix halo / vulkan : -DGGML_VULKAN=ON
rem   3090 / cuda         : -DGGML_CUDA=ON
set "CMAKE_BACKEND=auto"

rem cmake generator. auto keeps the cmake default, which on windows is visual studio, and
rem switches to ninja when cuda is picked but its msbuild integration is not installed.
rem pin a name to decide here, e.g. Ninja (needs cl and ninja on PATH)
set "GENERATOR=auto"

rem arguments added to every model run. auto gives -ngl 99, and on cuda -ncmoe 30 as well,
rem because the experts do not fit in 24 GB. -ncmoe depends on the card, so a different one
rem needs its own value here.
rem   strix halo, everything on the gpu : -ngl 99
rem   3090 + i9, moe experts on the cpu : -ngl 99 -ncmoe 30
set "EXTRA=auto"

rem how the weights are loaded. dio = unbuffered reads, none = read into memory without
rem mmap, auto = let llama.cpp pick (mmap). -lzm dio gathers the rows of the PLE table
rem with its own buffered row reads instead of page faults on a mapping: 12 gives it 343.3
rem t/s of prompt eval against 259.4 for -lzm on at the same PPL, and it leaves the 26.82 GiB
rem table on disk instead of mapping it
set "LOADMODE=-lm dio -lzm dio"

rem пары "-lm -lzm" для 10-load-time.bat, по одной загрузке модели на прогон. ленивый
rem тензор читается через mmap, а отображение файла заставляет windows согласовывать с
rem page cache каждое unbuffered чтение того же файла, по одному. поэтому важен и набор,
rem и порядок: сначала варианты без отображения, иначе следующий прогон читает файл уже
rem прогретым. "dio auto" проверяет забытый -lzm: на устройстве без mmap auto сводится к
rem dio, значит эти два прогона обязаны совпасть. -lzm off не меряем: он держит таблицу PLE
rem в памяти целиком (27 ГБ) и ничего не ускоряет
set "LOADVARIANTS="dio dio" "dio auto" "dio on" "none on" "mmap on""
set "LOADREPS=2"

rem how many times llama-bench repeats each measurement. llama-bench warms up before
rem every one of them, so a single repeat is already stable enough for the prefill
rem sweep; raise it only when two runs disagree
set "REPS=1"

rem prompt length and depths of the prefill sweep
set "NPROMPT=2048"
set "DEPTHS=0,32768,65536,122880"
set "UBATCH=512,2048"

rem arms swept by 04, 05, 06 and 07, one model load each. 1 is the build default, which
rem walks the list of cells the tile can see instead of all of KV. 0 is the plain dense
rem kernel. g and r are the two tile shapes of the gather, see 04-fa-sparse.bat. the
rem selection is the same in all of them, so this only moves speed. all four are vulkan
rem knobs, so auto keeps only arm 1 on another backend
set "FAVARIANTS=auto"

rem context and chunk count of the quality runs. the budget is a fixed ~513 blocks, so at a
rem short context it already covers most of the cache and the indexer is bypassed. keep the
rem context well above the budget or the numbers mean nothing
set "QCTX=32768"
set "QCHUNKS=4"

rem arms of 16-ctx.bat, "ctx ubatch". the compute reserve sizes on n_kv = n_ctx and on
rem n_tokens = min(n_ctx, n_ubatch), so both axes are swept. no weights are read, an arm
rem takes about a second
set "CTXVARIANTS="262144 2048" "262144 1024" "262144 512" "131072 2048" "131072 512" "65536 512" "32768 512""

rem the depth 07-perf-logger.bat measures at, the prompt length of the measured graph and its
rem ubatch. PERFPP=2048 PERFDEPTH=0 FAVARIANTS=1 gives one ubatch of 2048 at depth 0, the point gufo
rem reports its prefill split at (the sparse arms do not engage below the indexer budget)
set "PERFDEPTH=64000"
set "PERFPP=512"
set "PERFUB=2048"

rem 25-tile-sweep.bat: the medium quant tiles to try, each "BLOCK_SIZE,BM,BN,BK,WM,WN,WMITER,TM,TN,TK,WARP" in
rem quotes. (BM/WM)*(BN/WN) must be BLOCK_SIZE/WARP, BK 32, WARP the subgroup size (64 on strix halo) and TM,TN,TK
rem the coopmat shape (16). a wave holds (WM/16)*(WN/16) accumulators, that is what spills the large tile 128x128
rem on 128 threads (32 of them); on 512 threads the same tile keeps 8. the windows driver gives 32 KB of shared
rem memory: 256x64 and 256x128 do not fit. BM and BN are powers of two and at least BLOCK_SIZE/4 (one load
rem pass, 512 threads on a 64 side give wrong results). the build default
rem 128,64,64,32,64,32,2,16,16,16,64 always runs first
set "TILES="128,64,64,32,32,64,2,16,16,16,64" "256,64,64,32,32,32,2,16,16,16,64" "256,128,64,32,64,32,2,16,16,16,64" "256,128,64,32,32,64,2,16,16,16,64" "256,64,128,32,64,32,2,16,16,16,64" "256,64,128,32,32,64,2,16,16,16,64" "256,128,128,32,64,64,2,16,16,16,64" "512,128,128,32,64,32,2,16,16,16,64" "512,128,128,32,32,64,2,16,16,16,64" "128,128,32,32,64,32,2,16,16,16,64" "128,32,128,32,32,64,2,16,16,16,64""

rem 26-int8.bat: context and wikitext chunks of the KLD of the int8 coopmat path against the f16
rem path. the base logits file takes about INT8CTX x INT8CHUNKS x n_vocab x 2 bytes, for qwen4exp
rem 2048 x 4 x 248320 x 2 = about 4 GB, deleted at the end
set "INT8CTX=2048"
set "INT8CHUNKS=4"
rem chunks of "26-int8.bat kldlong": about 0.5 GB of base logits per chunk of 2048 (half of it is scored)
set "INT8LONGCHUNKS=32"

rem 19-decode-depth.bat: how the generation speed falls with the depth of the context.
rem the attention itself is capped by the indexer budget, but the block keys of the indexer
rem are rebuilt from the whole cache on every pass, so the decode is expected to grow with
rem n_kv. depth 0 is below the budget, where the indexer is bypassed entirely, so the first
rem point after it has to be well above ~2052 cells or the step would be read as depth.
rem the last depth plus DECNGEN must stay at or below 262144, the trained context
set "DECDEPTHS=0,4096,16384,32768,65536,131072,262080"
set "DECNGEN=64"
rem the batch only fills the depth, the measured pass generates one token
set "DECB=4096"
set "DECUB=2048"
rem depths at which 19 also takes the per-op breakdown, one model load each
set "DECPERFDEPTHS=16384 131072"

rem 20-moecache.bat: what a VRAM cache of the hot MoE experts gives and where the decode time goes,
rem one model load per arm, see the header of the script. a decode arm is "ctx np [args]": a
rem llama-completion run with MOENGEN sampled tokens, the context decides how much VRAM is left for
rem the cache, and each sequence gets ctx/np of the context. the args go to that arm only: the
rem second arm runs the real cache (--moe-cache) with all 48 MoE layers on the host and the free
rem VRAM in slots. the prompt is the head of MOEPROMPTFILE, the wikitext text unless _local.bat
rem points it at something else. MOEARGS goes into every arm: -fit off keeps -ncmoe from EXTRA, and
rem the -ub of models.ini belongs there too
set "MOEARMS="262144 1" "262144 1 -ncmoe 48 --moe-cache auto""
set "MOENGEN=2048"
set "MOECHARS=65536"
set "MOEARGS=-fit off"
rem a replay arm is "ub [args]": MOEREPLAYCHARS of text go through the model ub tokens per step
rem with -b = -ub and nothing is sampled, so all replay arms see the same routing
set "MOEREPLAY="1" "1 -ncmoe 48 --moe-cache auto" "4 -ncmoe 48 --moe-cache auto""
set "MOEREPLAYCHARS=16384"
set "MOEREPLAYCTX=262144"
rem a spec arm is "types [args]": llama-speculative-simple with the draft of SPECDRAFT and the
rem SPECNMAX and SPECPMIN of 17 below, skipped while SPECDRAFT is empty. none skips a list
set "MOESPEC="draft-mtp -ncmoe 48 --moe-cache auto" "draft-mtp -ncmoe 48 --moe-cache auto -cmoed" "ngram-mod,draft-mtp -ncmoe 48 --moe-cache auto""
set "MOESPECCTX=262144"
rem steps between two reports of the statistics, and graphs between two GGML_SCHED_PROF lines
set "MOEPERIOD=512"
rem nvidia-smi dmon during every arm: auto = on cuda when nvidia-smi is on the PATH, or 1 or 0
set "MOEDMON=auto"
set "MOEDMONGPU=0"

rem context llama-server is started with by 14-server.bat. the sweeps above stay shallow to
rem keep a research run cheap, the server does not have that reason: 262144 is the trained
rem context of qwen4exp, 0 takes it from the model
set "SRVCTX=262144"
set "SRVARGS=--host 127.0.0.1 --port 8080"

rem 17-spec-np.bat: does -np pay off under speculative decoding. SPECDRAFT is the MTP draft
rem gguf and has no default, the rest is a short run on purpose - the arms differ in how the
rem slots batch together, not in how deep the context is. every arm generates exactly SPECNGEN
rem tokens at temperature 0, so the arms are comparable; with sampling on they are not, two
rem runs of the same setting came out 7 percent apart
set "SPECDRAFT="
set "SPECCTX=32768"
set "SPECNMAX=6"
set "SPECPMIN=0.6"
set "SPECNGEN=512"
set "SPECPORT=8099"
set "SPECFIT=-fit off"
set "SPECVERB=4"
rem arms, see the header of 17-spec-np.bat. np2-lock minus np2-free is the price of splitting
rem one target pass into two ubatches, np1-noreuse is the price of rebuilding the target graph.
rem the ngram-* arms answer a different question - what ngram-mod is worth next to draft-mtp
set "SPECARMS=np1 np2-one np2-lock np2-free np1-noreuse ngram-off ngram-on ngram-crlf ngram-crlf-off ngram-miss"

rem 22-ubmem.bat: the memory and the speed of llama-server with -np 1, where the prefill and the
rem decode take turns. one server start per arm, see the header of the script. UBMEMSTATIC arms
rem run the static layout, UBMEMARMS arms run --phase-mem, none skips one kind. an arm is "ub" or
rem "ub ctx", auto ctx is SRVCTX. UBMEMARGS auto is the setup of models.ini: "-fit off -ncmoe 48
rem --moe-cache auto" on cuda, "-fit off" on vulkan. UBMEMDRAFT auto adds the MTP draft of
rem SPECDRAFT when that file exists. the long request is UBMEMFILL full ubatches and a half one of
rem the largest ub of all arms, the same prompt for every arm
set "UBMEMSTATIC=2048"
set "UBMEMARMS=8192 16384"
set "UBMEMCTX=auto"
set "UBMEMARGS=auto"
set "UBMEMDRAFT=auto"
set "UBMEMFILL=3"
set "UBMEMNGEN=256"
set "UBMEMPORT=8098"
rem seconds until /health answers after the start, and for one request
set "UBMEMWAIT=900"
set "UBMEMTIMEOUT=1800"

rem 23-spec-auto.bat: no speculation, ngram-mod, draft-mtp and both, fixed and with --spec-auto, see
rem the header of the script. an arm is "name types [args]", one server start each. every arm runs SPECAUTOPROMPTS x SPECAUTOSEEDS
rem chat requests of up to SPECAUTONGEN tokens with sampling on (SPECAUTOSAMP = temperature top-k
rem top-p, as in models.ini) and writes a per-cycle trace. SPECAUTOCTX auto is SRVCTX, SPECAUTOARGS
rem auto is the setup of models.ini, as UBMEMARGS. n6 is the arm the offline comparison uses: p-min
rem 0 drafts every position, so its trace holds the head probabilities of all six. auto is the fully
rem automatic setup: the type comes from the draft gguf, no n-max, so the cap is 6, and --spec-auto
rem adds ngram-mod itself. ng-n3 is its baseline with the same speculators. add
rem "n6p06 draft-mtp --spec-draft-n-max 6 --spec-draft-p-min 0.6" to check the old setting
set "SPECAUTOARMS="none none" "ng ngram-mod" "ng-auto ngram-mod --spec-auto" "n2 draft-mtp --spec-draft-n-max 2" "n3 draft-mtp --spec-draft-n-max 3" "n6 draft-mtp --spec-draft-n-max 6" "mtp-auto draft-mtp --spec-auto" "ng-n3 ngram-mod,draft-mtp --spec-draft-n-max 3" "auto infer --spec-auto""
set "SPECAUTOPROMPTS=os db code repeat"
set "SPECAUTOSEEDS=1 2"
set "SPECAUTONGEN=1024"
set "SPECAUTOCTX=auto"
set "SPECAUTOARGS=auto"
set "SPECAUTOSAMP=1.0 20 0.95"
set "SPECAUTOPORT=8097"
set "SPECAUTOWAIT=900"
set "SPECAUTOTIMEOUT=1800"

rem seconds to wait between two model loads in 07, 10 and 11. the model fills the gpu almost
rem completely and the driver frees it lazily, so a run started right after the previous one
rem dies in vkAllocateMemory
set "SETTLE=30"

rem PLE row cache settings compared by 11-ple-cache.bat, one model load each.
rem a variant is "readers blocksPerRequest", 0 = leave at the default.
rem the default sweep is the reader count, because that is the read queue depth: if the
rem time does not fall as it grows, the requests are serialized somewhere
set "PLEVARIANTS="1 64" "4 64" "16 64" "32 64""

rem what 13-disk-iops.bat asks diskspd for, one run each. a variant is
rem "blockKiB queueDepth threads"; 4 KiB is the page a row read pulls in, the 256 KiB run shows the
rem bandwidth ceiling of the disk. the row cache issues one blocking read per reader thread,
rem so "4 1 8" and "4 1 32" are its own pattern, and "4 8 4" / "4 32 4" are what the same
rem queue depth gives when one thread keeps several requests in flight
set "DISKVARIANTS="4 1 1" "4 1 8" "4 1 32" "4 8 4" "4 32 4" "256 32 4""
set "DISKSECS=15"

rem two extra arms of 13, both off by default because both touch the machine outside this
rem folder. DEFENDEREXCL=1 excludes the model file from the real time scanner for one sweep
rem (needs an elevated shell); RAMMAP is the full path to RAMMap64.exe, which can empty the
rem standby list and give the sweep a truly cold page cache
set "DEFENDEREXCL=0"
set "RAMMAP="

rem wikitext chunks of each of the two 12-ple-real.bat runs (-lzm on and -lzm dio)
set "PLECHUNKS=16"

rem what run-all.bat runs, 1 = run, 0 = skip. all of them run by default: a full sweep
rem takes hours, so set the ones you do not need to 0 in _local.bat. 14-server is not a
rem measurement and is never called from run-all
rem   00 - configure and build, a failed build stops the run
set "RUN_BUILD=1"
rem   01 02 03 04 - correctness and prefill speed, the point of the folder
set "RUN_PREFILL=1"
rem   05 - perplexity, run-all downloads the wikitext text if it is missing
set "RUN_QUALITY=1"
rem   06 - kl divergence, needs about 10 GB of disk
set "RUN_KL=1"
rem   07 10 - per-op timings, load time
set "RUN_TIMING=1"
rem   08 16 - model diagnostics and the compute buffer against the context, useful when
rem           the model refuses to load or the context does not fit
set "RUN_DIAG=1"
rem   11 12 - PLE row cache (-lzm dio) against lazy mmap, on random tokens and on real
rem           text; one model load per variant, so both are slow
set "RUN_PLE=1"
rem   13 - raw disk IOPS behind -lzm dio, needs diskspd (downloaded on first run)
set "RUN_DISK=1"
rem   15 - test-backend-ops on the MUL_MAT_ID epilogue, no model. vulkan only, auto turns it
rem        off on another backend
set "RUN_MMID=auto"
rem   17 - does -np pay off under speculative decoding, one server start per arm. off by
rem        default: it needs SPECDRAFT, which most setups do not have
set "RUN_SPEC=0"
rem   19 - generation speed against the depth of the context, plus the per-op breakdown.
rem        off by default: the sweep spends about an hour filling the deep contexts
set "RUN_DECODE=0"
rem   20 - what a VRAM cache of the hot MoE experts would give, from the routing of a real text.
rem        auto runs it on cuda only: there -ncmoe keeps the experts of the first layers in host
rem        memory, on the strix halo every expert is in VRAM already and the report is one line
set "RUN_MOECACHE=auto"
rem   22 - does the server survive a prefill and a decode in turn at a large -ub. off by
rem        default: one server start at the full context per arm
set "RUN_UBMEM=0"
rem   23 - fixed draft lengths against --spec-auto. off by default: it needs SPECDRAFT, and it is
rem        one server start at the full context per arm
set "RUN_SPECAUTO=0"

rem ===================================================================
rem  machine-specific overrides. _local.bat is not tracked by git, so
rem  keeping MODEL and the backend there stops `git pull` from colliding
rem  with edits to this file. it runs after the defaults above and before
rem  anything derived from them. see _local.example.bat
rem ===================================================================
if exist "%~dp0_local.bat" call "%~dp0_local.bat"

rem ===================================================================
rem  derived, no need to touch
rem ===================================================================
for %%i in ("%BUILD%") do set "BUILD=%%~fi"

rem resolve the backend. BACKEND is the short name the other scripts branch on
if /i not "%CMAKE_BACKEND%"=="auto" goto :backend_set
set "CMAKE_BACKEND="
where nvcc >nul 2>&1
if not errorlevel 1 set "CMAKE_BACKEND=-DGGML_CUDA=ON"
if defined CMAKE_BACKEND goto :backend_set
if defined CUDA_PATH set "CMAKE_BACKEND=-DGGML_CUDA=ON"
if defined CMAKE_BACKEND goto :backend_set
if defined VULKAN_SDK set "CMAKE_BACKEND=-DGGML_VULKAN=ON"
if defined CMAKE_BACKEND goto :backend_set
where glslc >nul 2>&1
if not errorlevel 1 set "CMAKE_BACKEND=-DGGML_VULKAN=ON"
:backend_set

set "BACKEND=cpu"
rem as in 00-build.bat: a replace in an undefined CMAKE_BACKEND breaks the line before its if runs
if not defined CMAKE_BACKEND goto :backend_named
if not "%CMAKE_BACKEND:GGML_VULKAN=%"=="%CMAKE_BACKEND%" set "BACKEND=vulkan"
if not "%CMAKE_BACKEND:GGML_CUDA=%"=="%CMAKE_BACKEND%" set "BACKEND=cuda"
:backend_named

rem defaults that follow from the backend
if /i not "%EXTRA%"=="auto" goto :extra_set
set "EXTRA=-ngl 99"
if /i "%BACKEND%"=="cuda" set "EXTRA=-ngl 99 -ncmoe 30"
:extra_set

if /i not "%FAVARIANTS%"=="auto" goto :fa_set
set "FAVARIANTS=1 0 g r"
if /i not "%BACKEND%"=="vulkan" set "FAVARIANTS=1"
:fa_set

if /i not "%RUN_MMID%"=="auto" goto :mmid_set
set "RUN_MMID=1"
if /i not "%BACKEND%"=="vulkan" set "RUN_MMID=0"
:mmid_set

if /i not "%RUN_MOECACHE%"=="auto" goto :moecache_set
set "RUN_MOECACHE=1"
if /i not "%BACKEND%"=="cuda" set "RUN_MOECACHE=0"
:moecache_set

rem multi-config generators (msvc) put the binaries in bin\Release, single-config in bin
set "BIN=%BUILD%\bin\Release"
if not exist "%BIN%" set "BIN=%BUILD%\bin"

set "LOGS=%~dp0logs"
if not exist "%LOGS%" mkdir "%LOGS%"

for /f %%i in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd-HHmmss"') do set "TS=%%i"
