@echo off
rem ===================================================================
rem  defaults for every other .bat in this folder, which all call this
rem  one first. do not edit this file on the test machine: put the local
rem  values in _local.bat instead, it is ignored by git.
rem ===================================================================

rem git bash / msys ships its own find, sort and friends, and puts them ahead of the windows
rem ones on PATH. the msys find does not understand /i, so `tasklist | find /i` fails there.
rem every script in this folder runs inside setlocal, so this stays in the script
set "PATH=%SystemRoot%\System32;%SystemRoot%;%SystemRoot%\System32\Wbem;%PATH%"

rem full path to the gguf
set "MODEL=C:\models\qwen3-next.gguf"

rem plain text file for the quality runs (get-wikitext.bat downloads one)
set "PPLFILE=%~dp0wikitext-2-raw\wiki.test.raw"

rem build directory, created by 00-build.bat
set "BUILD=%~dp0..\..\build-win"

rem backend for cmake. auto picks from what the machine has: nvcc or CUDA_PATH -> cuda,
rem else VULKAN_SDK or glslc -> vulkan, else a cpu only build. cuda wins when both are
rem installed. pin it instead of auto to decide here:
rem   strix halo / vulkan : -DGGML_VULKAN=ON
rem   3090 / cuda         : -DGGML_CUDA=ON
set "CMAKE_BACKEND=auto"

rem arguments added to every model run. auto gives -ngl 99, and on cuda -ncmoe 30 as well,
rem because the experts do not fit in 24 GB. -ncmoe depends on the card, so a different one
rem needs its own value here.
rem   strix halo, everything on the gpu : -ngl 99
rem   3090 + i9, moe experts on the cpu : -ngl 99 -ncmoe 30
set "EXTRA=auto"

rem how the weights are loaded. dio = unbuffered reads, none = read into memory without
rem mmap, auto = let llama.cpp pick (mmap). -lzm dio gathers the rows of the PLE table
rem through an own block cache instead of the page cache: 12 gives it 343.3 t/s of prompt
rem eval against 259.4 for -lzm on at the same PPL, and it leaves the 26.82 GiB table on
rem disk instead of mapping it
set "LOADMODE=-lm dio -lzm dio"

rem пары "-lm -lzm" для 10-load-time.bat, по одной загрузке модели на прогон. ленивый
rem тензор читается через mmap, а отображение файла заставляет windows согласовывать с
rem page cache каждое unbuffered чтение того же файла, по одному. поэтому важен и набор,
rem и порядок: сначала варианты без отображения, иначе следующий прогон читает файл уже
rem прогретым. "dio auto" проверяет забытый -lzm: на устройстве без mmap auto сводится к
rem dio, значит эти два прогона обязаны совпасть. -lzm off не меряем: он держит таблицу PLE
rem в памяти целиком (27 ГБ) и ничего не ускоряет
set "LOADVARIANTS="dio dio" "dio auto" "dio on" "none on" "mmap on""
set "LOADREPS=2"

rem how many times llama-bench repeats each measurement. llama-bench warms up before
rem every one of them, so a single repeat is already stable enough for the prefill
rem sweep; raise it only when two runs disagree
set "REPS=1"

rem prompt length and depths of the prefill sweep
set "NPROMPT=2048"
set "DEPTHS=0,32768,65536,122880"
set "UBATCH=512,2048"

rem arms swept by 04, 05, 06 and 07, one model load each. 1 is the build default, which
rem walks the list of cells the tile can see instead of all of KV. 0 is the plain dense
rem kernel. g and r are the two tile shapes of the gather, see 04-fa-sparse.bat. the
rem selection is the same in all of them, so this only moves speed. all four are vulkan
rem knobs, so auto keeps only arm 1 on another backend
set "FAVARIANTS=auto"

rem context and chunk count of the quality runs. the budget is a fixed ~513 blocks, so at a
rem short context it already covers most of the cache and the indexer is bypassed. keep the
rem context well above the budget or the numbers mean nothing
set "QCTX=32768"
set "QCHUNKS=4"

rem arms of 16-ctx.bat, "ctx ubatch". the compute reserve sizes on n_kv = n_ctx and on
rem n_tokens = min(n_ctx, n_ubatch), so both axes are swept. no weights are read, an arm
rem takes about a second
set "CTXVARIANTS="262144 2048" "262144 1024" "262144 512" "131072 2048" "131072 512" "65536 512" "32768 512""

rem the depth 07-perf-logger.bat measures at
set "PERFDEPTH=64000"

rem 19-decode-depth.bat: how the generation speed falls with the depth of the context.
rem the attention itself is capped by the indexer budget, but the block keys of the indexer
rem are rebuilt from the whole cache on every pass, so the decode is expected to grow with
rem n_kv. depth 0 is below the budget, where the indexer is bypassed entirely, so the first
rem point after it has to be well above ~2052 cells or the step would be read as depth.
rem the last depth plus DECNGEN must stay at or below 262144, the trained context
set "DECDEPTHS=0,4096,16384,32768,65536,131072,262080"
set "DECNGEN=64"
rem the batch only fills the depth, the measured pass generates one token
set "DECB=4096"
set "DECUB=2048"
rem depths at which 19 also takes the per-op breakdown, one model load each
set "DECPERFDEPTHS=16384 131072"

rem context llama-server is started with by 14-server.bat. the sweeps above stay shallow to
rem keep a research run cheap, the server does not have that reason: 262144 is the trained
rem context of qwen4exp, 0 takes it from the model
set "SRVCTX=262144"
set "SRVARGS=--host 127.0.0.1 --port 8080"

rem 17-spec-np.bat: does -np pay off under speculative decoding. SPECDRAFT is the MTP draft
rem gguf and has no default, the rest is a short run on purpose - the arms differ in how the
rem slots batch together, not in how deep the context is. every arm generates exactly SPECNGEN
rem tokens at temperature 0, so the arms are comparable; with sampling on they are not, two
rem runs of the same setting came out 7 percent apart
set "SPECDRAFT="
set "SPECCTX=32768"
set "SPECNMAX=6"
set "SPECPMIN=0.6"
set "SPECNGEN=512"
set "SPECPORT=8099"
set "SPECFIT=-fit off"
set "SPECVERB=4"
rem arms, see the header of 17-spec-np.bat. np2-lock minus np2-free is the price of splitting
rem one target pass into two ubatches, np1-noreuse is the price of rebuilding the target graph.
rem the ngram-* arms answer a different question - what ngram-mod is worth next to draft-mtp
set "SPECARMS=np1 np2-one np2-lock np2-free np1-noreuse ngram-off ngram-on ngram-crlf ngram-crlf-off ngram-miss"

rem seconds to wait between two model loads in 07, 10 and 11. the model fills the gpu almost
rem completely and the driver frees it lazily, so a run started right after the previous one
rem dies in vkAllocateMemory
set "SETTLE=30"

rem PLE row cache settings compared by 11-ple-cache.bat, one model load each.
rem a variant is "readers blockBytes blocksPerRequest", 0 = leave at the default.
rem the default sweep is the reader count, because that is the read queue depth: if the
rem time does not fall as it grows, the requests are serialized somewhere
set "PLEVARIANTS="1 0 64" "4 0 64" "16 0 64" "32 0 64""

rem what 13-disk-iops.bat asks diskspd for, one run each. a variant is
rem "blockKiB queueDepth threads"; 4 KiB is the row cache block, the 256 KiB run shows the
rem bandwidth ceiling of the disk. the row cache issues one blocking read per reader thread,
rem so "4 1 8" and "4 1 32" are its own pattern, and "4 8 4" / "4 32 4" are what the same
rem queue depth gives when one thread keeps several requests in flight
set "DISKVARIANTS="4 1 1" "4 1 8" "4 1 32" "4 8 4" "4 32 4" "256 32 4""
set "DISKSECS=15"

rem two extra arms of 13, both off by default because both touch the machine outside this
rem folder. DEFENDEREXCL=1 excludes the model file from the real time scanner for one sweep
rem (needs an elevated shell); RAMMAP is the full path to RAMMap64.exe, which can empty the
rem standby list and give the sweep a truly cold page cache
set "DEFENDEREXCL=0"
set "RAMMAP="

rem what 12-ple-real.bat compares on real text, one model load each. a variant is the block
rem size in bytes, 0 = leave at the default, which is one row
set "PLEREALVARIANTS=0"
set "PLECHUNKS=16"

rem what run-all.bat runs, 1 = run, 0 = skip. all of them run by default: a full sweep
rem takes hours, so set the ones you do not need to 0 in _local.bat. 14-server is not a
rem measurement and is never called from run-all
rem   00 - configure and build, a failed build stops the run
set "RUN_BUILD=1"
rem   01 02 03 04 - correctness and prefill speed, the point of the folder
set "RUN_PREFILL=1"
rem   05 - perplexity, run-all downloads the wikitext text if it is missing
set "RUN_QUALITY=1"
rem   06 - kl divergence, needs about 10 GB of disk
set "RUN_KL=1"
rem   07 09 10 - per-op timings, buffer allocation, load time
set "RUN_TIMING=1"
rem   08 16 - model diagnostics and the compute buffer against the context, useful when
rem           the model refuses to load or the context does not fit
set "RUN_DIAG=1"
rem   11 12 - PLE row cache (-lzm dio) against lazy mmap, on random tokens and on real
rem           text; one model load per variant, so both are slow
set "RUN_PLE=1"
rem   13 - raw disk IOPS behind -lzm dio, needs diskspd (downloaded on first run)
set "RUN_DISK=1"
rem   15 - MUL_MAT_ID tuning, one model load per arm, so it is slow. vulkan only, auto
rem        turns it off on another backend
set "RUN_MMID=auto"
rem   17 - does -np pay off under speculative decoding, one server start per arm. off by
rem        default: it needs SPECDRAFT, which most setups do not have
set "RUN_SPEC=0"
rem   19 - generation speed against the depth of the context, plus the per-op breakdown.
rem        off by default: the sweep spends about an hour filling the deep contexts
set "RUN_DECODE=0"

rem ===================================================================
rem  machine-specific overrides. _local.bat is not tracked by git, so
rem  keeping MODEL and the backend there stops `git pull` from colliding
rem  with edits to this file. it runs after the defaults above and before
rem  anything derived from them. see _local.example.bat
rem ===================================================================
if exist "%~dp0_local.bat" call "%~dp0_local.bat"

rem ===================================================================
rem  derived, no need to touch
rem ===================================================================
for %%i in ("%BUILD%") do set "BUILD=%%~fi"

rem resolve the backend. BACKEND is the short name the other scripts branch on
if /i not "%CMAKE_BACKEND%"=="auto" goto :backend_set
set "CMAKE_BACKEND="
where nvcc >nul 2>&1
if not errorlevel 1 set "CMAKE_BACKEND=-DGGML_CUDA=ON"
if defined CMAKE_BACKEND goto :backend_set
if defined CUDA_PATH set "CMAKE_BACKEND=-DGGML_CUDA=ON"
if defined CMAKE_BACKEND goto :backend_set
if defined VULKAN_SDK set "CMAKE_BACKEND=-DGGML_VULKAN=ON"
if defined CMAKE_BACKEND goto :backend_set
where glslc >nul 2>&1
if not errorlevel 1 set "CMAKE_BACKEND=-DGGML_VULKAN=ON"
:backend_set

set "BACKEND=cpu"
if not "%CMAKE_BACKEND:GGML_VULKAN=%"=="%CMAKE_BACKEND%" set "BACKEND=vulkan"
if not "%CMAKE_BACKEND:GGML_CUDA=%"=="%CMAKE_BACKEND%" set "BACKEND=cuda"

rem defaults that follow from the backend
if /i not "%EXTRA%"=="auto" goto :extra_set
set "EXTRA=-ngl 99"
if /i "%BACKEND%"=="cuda" set "EXTRA=-ngl 99 -ncmoe 30"
:extra_set

if /i not "%FAVARIANTS%"=="auto" goto :fa_set
set "FAVARIANTS=1 0 g r"
if /i not "%BACKEND%"=="vulkan" set "FAVARIANTS=1"
:fa_set

if /i not "%RUN_MMID%"=="auto" goto :mmid_set
set "RUN_MMID=1"
if /i not "%BACKEND%"=="vulkan" set "RUN_MMID=0"
:mmid_set

rem multi-config generators (msvc) put the binaries in bin\Release, single-config in bin
set "BIN=%BUILD%\bin\Release"
if not exist "%BIN%" set "BIN=%BUILD%\bin"

set "LOGS=%~dp0logs"
if not exist "%LOGS%" mkdir "%LOGS%"

for /f %%i in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd-HHmmss"') do set "TS=%%i"
